print("Welcome to the tip calculator")
bill=float(input("What was the total bill? ₹"))
tip=int(input("What percentage tip do you want to give? 10% or 12% or 15% "))
people=int(input("How many people to split the bill? "))
total_bill=bill*(1+tip/100)
bill_per_person=round(total_bill/people, 2)
print(f"Each person should pay: {bill_per_person}.")
